services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9997:9997"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_HOSTNAME: kafka

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka_server:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER_CONNECT: zookeeper:2181
      DYNAMIC_CONFIG_ENABLED: true

  api_gateway:
    build:
      context: .
      dockerfile: api_gateway.dockerfile
    container_name: api_gateway
    ports:
      - "8000:8000"
    depends_on:
      - user_service
      - post_service
    environment:
      USER_SERVICE_URL: "http://user_service:8001"
      POST_SERVER_ADDR: "post_service:51075"
      POST_SERVER_PORT: 51075

  user_service:
    build: user_service
    container_name: user_service
    ports:
      - "8001:8001"
    depends_on:
      - user_postgres
      - kafka
    environment:
      DB_HOST: user_postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: user_db
      PRIVATE_KEY_PATH: /secrets/signature.pem
      PUBLIC_KEY_PATH: /secrets/signature.pub
      ALGORITHM: RS256
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
    volumes:
      - ./secrets:/secrets

  post_service:
    build:
      context: .
      dockerfile: post_service.dockerfile
    container_name: post_service
    ports:
      - "51075:51075"
    depends_on:
      - post_postgres
      - kafka
    environment:
      POST_DB_HOST: post_postgres
      POST_DB_PORT: 5432
      POST_DB_USER: padmin
      POST_DB_PASSWORD: padmin
      POST_DB_NAME: post_db
      POST_SERVER_PORT: 51075
      POST_SERVER_ADDR: "0.0.0.0:51075"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"

  post_postgres:
    image: postgres:latest
    container_name: post_db_container
    environment:
      POSTGRES_USER: padmin
      POSTGRES_PASSWORD: padmin
      POSTGRES_DB: post_db
    ports:
      - "5433:5432"
    volumes:
      - post_db_data:/var/lib/postgresql/data

  user_postgres:
    image: postgres:latest
    container_name: user_db_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data

  tests:
    build:
      context: .
      dockerfile: tests/Dockerfile
    environment:
      POST_SERVER_ADDR: "post_service:51075"
      USER_GATEWAY_URL: "http://user_service:8001"
    depends_on:
      - post_service
      - user_service

volumes:
  post_db_data:
    driver: local
  user_db_data:
    driver: local