services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - user-service
    environment:
      USER_SERVICE_URL: "http://user-service:8001"

  user-service:
    build: ./user-service
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USER: "user1"
      DB_PASSWORD: "password"
      DB_NAME: "userdb"
      PRIVATE_KEY_PATH: "/app/secrets/signature.pem"
      PUBLIC_KEY_PATH: "/app/secrets/signature.pub"
      ALGORITHM: "RS256"
    volumes:
      - ./secrets:/app/secrets

  db:
    image: postgres:13
    container_name: postgres_fast_api
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local