services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9997:9997"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_HOSTNAME: kafka

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER_CONNECT: zookeeper:2181
      DYNAMIC_CONFIG_ENABLED: true

  api_gateway:
    build:
      context: .
      dockerfile: api_gateway.dockerfile
    container_name: api_gateway
    ports:
      - "8000:8000"
    depends_on:
      - user_service
      - post_service
      - stats_service
    environment:
      USER_SERVICE_URL: "http://user_service:8001"
      POST_SERVER_ADDR: "post_service:51075"
      STATS_SERVER_ADDR: "stats_service:50052"
      POST_SERVER_PORT: 51075
      STATS_SERVER_PORT: 50052

  user_service:
    build: user_service
    container_name: user_service
    ports:
      - "8001:8001"
    depends_on:
      - user_postgres
      - kafka
    environment:
      DB_HOST: user_postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: user_db
      PRIVATE_KEY_PATH: /secrets/signature.pem
      PUBLIC_KEY_PATH: /secrets/signature.pub
      ALGORITHM: RS256
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
    volumes:
      - ./secrets:/secrets

  post_service:
    build:
      context: .
      dockerfile: post_service.dockerfile
    container_name: post_service
    ports:
      - "51075:51075"
    depends_on:
      - post_postgres
      - kafka
    environment:
      POST_DB_HOST: post_postgres
      POST_DB_PORT: 5432
      POST_DB_USER: padmin
      POST_DB_PASSWORD: padmin
      POST_DB_NAME: post_db
      POST_SERVER_PORT: 51075
      POST_SERVER_ADDR: "0.0.0.0:51075"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"

  post_postgres:
    image: postgres:latest
    platform: linux/amd64
    container_name: post_db_container
    environment:
      POSTGRES_USER: padmin
      POSTGRES_PASSWORD: padmin
      POSTGRES_DB: post_db
    ports:
      - "5433:5432"
    volumes:
      - post_db_data:/var/lib/postgresql/data

  user_postgres:
    image: postgres:latest
    platform: linux/amd64
    container_name: user_db_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    platform: linux/amd64
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse-config/users.d/:/etc/clickhouse-server/users.d/

  stats_service:
    build:
      context: .
      dockerfile: stats_service.dockerfile
    container_name: stats_service
    depends_on:
      - kafka
      - clickhouse
    ports:
      - "50052:50052"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 9000
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ""
      STATS_SERVER_PORT: 50052

  tests:
    build:
      context: .
      dockerfile: tests/Dockerfile
    environment:
      POST_SERVER_ADDR: "post_service:51075"
      USER_GATEWAY_URL: "http://user_service:8001"
      USER_SERVICE_URL: "http://user_service:8001"
      STATS_SERVER_ADDR: "stats_service:50052"
      POST_SERVER_PORT: 51075
      STATS_SERVER_PORT: 50052
      TEST: "true"
    depends_on:
      - post_service
      - user_service

  tests2:
    build:
      context: .
      dockerfile: tests2/Dockerfile
    container_name: tests2
    depends_on:
      - kafka
      - stats_service
    volumes:
      - ./user_service:/app/user_service:ro
      - ./post_service:/app/post_service:ro
      - ./stats_service:/app/stats_service:ro
      - ./tests2:/app/tests:ro
      - ./proto:/app/proto:ro
      - ./requirements.txt:/app/requirements.txt:ro
      - ./pytest.ini:/app/pytest.ini:ro
    environment:
      PYTHONPATH: "/app/user_service:/app/post_service:/app/stats_service:/app/proto:/app"
      TEST: "true"

      DB_HOST: localhost
      POST_DB_HOST: localhost
      DB_PORT: "5432"
      POST_DB_PORT: "5432"
      DB_NAME: test_db
      POST_DB_NAME: test_db
      DB_USER: test_user
      POST_DB_USER: test_user
      DB_PASSWORD: test_password
      POST_DB_PASSWORD: test_password
      PRIVATE_KEY_PATH: "/dev/null"
      PUBLIC_KEY_PATH: "/dev/null"
      ALGORITHM: HS256
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      POST_SERVER_PORT: 51075
      POST_SERVER_ADDR: "0.0.0.0:51075"
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 9000
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ""
      STATS_SERVER_PORT: 50052

  tests3:
    build:
      context: .
      dockerfile: tests3/Dockerfile
    container_name: tests3
    volumes:
      - ./pytest.ini:/app/pytest.ini:ro
    depends_on:
      - api_gateway
      - user_service
      - post_service
      - stats_service
      - kafka
      - clickhouse
      - user_postgres
      - post_postgres
    environment:
      USER_SERVICE_URL: "http://user_service:8001"
      POST_SERVER_ADDR: "post_service:51075"
      STATS_SERVER_ADDR: "stats_service:50052"
      POST_SERVER_PORT: 51075
      STATS_SERVER_PORT: 50052
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 9000
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ""
      PYTHONPATH: "/app/proto:/app"

volumes:
  post_db_data:
    driver: local
  user_db_data:
    driver: local
  clickhouse_data:
    driver: local