# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import stats_pb2 as stats__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in stats_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StatServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPostStats = channel.unary_unary(
                '/stats.StatService/GetPostStats',
                request_serializer=stats__pb2.PostRequest.SerializeToString,
                response_deserializer=stats__pb2.PostStats.FromString,
                _registered_method=True)
        self.GetViewsDynamics = channel.unary_unary(
                '/stats.StatService/GetViewsDynamics',
                request_serializer=stats__pb2.PostRequest.SerializeToString,
                response_deserializer=stats__pb2.PostDynamics.FromString,
                _registered_method=True)
        self.GetLikesDynamics = channel.unary_unary(
                '/stats.StatService/GetLikesDynamics',
                request_serializer=stats__pb2.PostRequest.SerializeToString,
                response_deserializer=stats__pb2.PostDynamics.FromString,
                _registered_method=True)
        self.GetCommentsDynamics = channel.unary_unary(
                '/stats.StatService/GetCommentsDynamics',
                request_serializer=stats__pb2.PostRequest.SerializeToString,
                response_deserializer=stats__pb2.PostDynamics.FromString,
                _registered_method=True)
        self.GetTopPosts = channel.unary_unary(
                '/stats.StatService/GetTopPosts',
                request_serializer=stats__pb2.TopRequest.SerializeToString,
                response_deserializer=stats__pb2.TopPostsResponse.FromString,
                _registered_method=True)
        self.GetTopUsers = channel.unary_unary(
                '/stats.StatService/GetTopUsers',
                request_serializer=stats__pb2.TopRequest.SerializeToString,
                response_deserializer=stats__pb2.TopUsersResponse.FromString,
                _registered_method=True)


class StatServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPostStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetViewsDynamics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLikesDynamics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCommentsDynamics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopPosts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPostStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPostStats,
                    request_deserializer=stats__pb2.PostRequest.FromString,
                    response_serializer=stats__pb2.PostStats.SerializeToString,
            ),
            'GetViewsDynamics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetViewsDynamics,
                    request_deserializer=stats__pb2.PostRequest.FromString,
                    response_serializer=stats__pb2.PostDynamics.SerializeToString,
            ),
            'GetLikesDynamics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLikesDynamics,
                    request_deserializer=stats__pb2.PostRequest.FromString,
                    response_serializer=stats__pb2.PostDynamics.SerializeToString,
            ),
            'GetCommentsDynamics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCommentsDynamics,
                    request_deserializer=stats__pb2.PostRequest.FromString,
                    response_serializer=stats__pb2.PostDynamics.SerializeToString,
            ),
            'GetTopPosts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopPosts,
                    request_deserializer=stats__pb2.TopRequest.FromString,
                    response_serializer=stats__pb2.TopPostsResponse.SerializeToString,
            ),
            'GetTopUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopUsers,
                    request_deserializer=stats__pb2.TopRequest.FromString,
                    response_serializer=stats__pb2.TopUsersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stats.StatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stats.StatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StatService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPostStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stats.StatService/GetPostStats',
            stats__pb2.PostRequest.SerializeToString,
            stats__pb2.PostStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetViewsDynamics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stats.StatService/GetViewsDynamics',
            stats__pb2.PostRequest.SerializeToString,
            stats__pb2.PostDynamics.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLikesDynamics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stats.StatService/GetLikesDynamics',
            stats__pb2.PostRequest.SerializeToString,
            stats__pb2.PostDynamics.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCommentsDynamics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stats.StatService/GetCommentsDynamics',
            stats__pb2.PostRequest.SerializeToString,
            stats__pb2.PostDynamics.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTopPosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stats.StatService/GetTopPosts',
            stats__pb2.TopRequest.SerializeToString,
            stats__pb2.TopPostsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTopUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stats.StatService/GetTopUsers',
            stats__pb2.TopRequest.SerializeToString,
            stats__pb2.TopUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
