# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stats.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'stats.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstats.proto\x12\x05stats\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"L\n\tPostStats\x12\x0f\n\x07post_id\x18\x01 \x01(\x05\x12\r\n\x05views\x18\x02 \x01(\x03\x12\r\n\x05likes\x18\x03 \x01(\x03\x12\x10\n\x08\x63omments\x18\x04 \x01(\x03\"(\n\tDateCount\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x03\"?\n\x0cPostDynamics\x12\x0f\n\x07post_id\x18\x01 \x01(\x05\x12\x1e\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x10.stats.DateCount\"*\n\x08PostRank\x12\x0f\n\x07post_id\x18\x01 \x01(\x05\x12\r\n\x05\x63ount\x18\x02 \x01(\x03\"*\n\x08UserRank\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x03\"2\n\x10TopPostsResponse\x12\x1e\n\x05items\x18\x01 \x03(\x0b\x32\x0f.stats.PostRank\"2\n\x10TopUsersResponse\x12\x1e\n\x05items\x18\x01 \x03(\x0b\x32\x0f.stats.UserRank\"\x1e\n\x0bPostRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\x05\"+\n\nTopRequest\x12\x1d\n\x06metric\x18\x01 \x01(\x0e\x32\r.stats.Metric*,\n\x06Metric\x12\t\n\x05VIEWS\x10\x00\x12\t\n\x05LIKES\x10\x01\x12\x0c\n\x08\x43OMMENTS\x10\x02\x32\xf3\x02\n\x0bStatService\x12\x34\n\x0cGetPostStats\x12\x12.stats.PostRequest\x1a\x10.stats.PostStats\x12;\n\x10GetViewsDynamics\x12\x12.stats.PostRequest\x1a\x13.stats.PostDynamics\x12;\n\x10GetLikesDynamics\x12\x12.stats.PostRequest\x1a\x13.stats.PostDynamics\x12>\n\x13GetCommentsDynamics\x12\x12.stats.PostRequest\x1a\x13.stats.PostDynamics\x12\x39\n\x0bGetTopPosts\x12\x11.stats.TopRequest\x1a\x17.stats.TopPostsResponse\x12\x39\n\x0bGetTopUsers\x12\x11.stats.TopRequest\x1a\x17.stats.TopUsersResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stats_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_METRIC']._serialized_start=538
  _globals['_METRIC']._serialized_end=582
  _globals['_POSTSTATS']._serialized_start=84
  _globals['_POSTSTATS']._serialized_end=160
  _globals['_DATECOUNT']._serialized_start=162
  _globals['_DATECOUNT']._serialized_end=202
  _globals['_POSTDYNAMICS']._serialized_start=204
  _globals['_POSTDYNAMICS']._serialized_end=267
  _globals['_POSTRANK']._serialized_start=269
  _globals['_POSTRANK']._serialized_end=311
  _globals['_USERRANK']._serialized_start=313
  _globals['_USERRANK']._serialized_end=355
  _globals['_TOPPOSTSRESPONSE']._serialized_start=357
  _globals['_TOPPOSTSRESPONSE']._serialized_end=407
  _globals['_TOPUSERSRESPONSE']._serialized_start=409
  _globals['_TOPUSERSRESPONSE']._serialized_end=459
  _globals['_POSTREQUEST']._serialized_start=461
  _globals['_POSTREQUEST']._serialized_end=491
  _globals['_TOPREQUEST']._serialized_start=493
  _globals['_TOPREQUEST']._serialized_end=536
  _globals['_STATSERVICE']._serialized_start=585
  _globals['_STATSERVICE']._serialized_end=956
# @@protoc_insertion_point(module_scope)
